require_relative 'spec_helper'

# http://adventofcode.com/2024/day/8

describe Day8 do
  let(:overall_scenario_input) {
    <<~STRING
      ............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............
    STRING
  }

  describe "part1" do
    it "overall scenario" do
      expected = 14
      actual = Day8.part1(overall_scenario_input)
      _(actual).must_equal(expected)
    end
  end

  describe Day8::Map do
    describe "antenna_types" do
      it "returns the antenna types in the grid" do
        expected = ["0", "A"]
        actual = Day8::Map.new(overall_scenario_input).antenna_types
        _(actual).must_equal(expected)
      end
    end

    describe "antinodes_for_antenna_type(antenna_type)" do
      it "answers correctly when nodes are on the diagonal" do
        input =
          <<~STRING
            ..........
            ..........
            ..........
            ....a.....
            ..........
            .....a....
            ..........
            ..........
            ..........
            ..........
          STRING
        output =
          <<~STRING
            ..........
            ...#......
            ..........
            ....a.....
            ..........
            .....a....
            ..........
            ......#...
            ..........
            ..........
          STRING
        expected = Day8::Map.new(output).find_all('#')
        actual = Day8::Map.new(input).antinodes_for_antenna_type('a')
        _(actual).must_equal(expected)
      end

      it "answers correctly when nodes are a triangle" do
        input =
          <<~STRING
            ..........
            ..........
            ..........
            ....a.....
            ........a.
            .....a....
            ..........
            ..........
            ..........
            ..........
          STRING
        output =
          <<~STRING
            ..........
            ...#......
            #.........
            ....a.....
            ........a.
            .....a....
            ..#.......
            ......#...
            ..........
            ..........
          STRING
        expected = Day8::Map.new(output).find_all('#')
        actual = Day8::Map.new(input).antinodes_for_antenna_type('a')
        _(actual.sort).must_equal(expected)
      end

      it "answers correctly when nodes are mixed" do
        input =
          <<~STRING
            ..........
            ..........
            ..........
            ....a.....
            ........a.
            .....a....
            ..........
            ......A...
            ..........
            ..........
          STRING
        output =
          <<~STRING
            ..........
            ...#......
            #.........
            ....a.....
            ........a.
            .....a....
            ..#.......
            ......#...
            ..........
            ..........
          STRING
        expected = Day8::Map.new(output).find_all('#')
        actual = Day8::Map.new(input).antinodes_for_antenna_type('a')
        _(actual.sort).must_equal(expected)
      end
    end

    describe "antinode_locations" do
      it "answers correctly when nodes are mixed and overlapping" do
        input =
          <<~STRING
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
          STRING
        output =
          <<~STRING
            ......#....#
            ...#....0...
            ....#0....#.
            ..#....0....
            ....0....#..
            .#....#.....
            ...#........
            #......#....
            ........A...
            .........A..
            ..........#.
            ..........#.
          STRING
        expected = Day8::Map.new(output).find_all('#')
        actual = Day8::Map.new(input).antinode_locations
        _(actual.sort).must_equal(expected)
      end
    end
  end

  describe "part2" do
    it "overall scenario" do
      input = "TBD"
      expected = "TBD"
      actual = Day8.part2(input)
      _(actual).must_equal(expected)
    end
  end
end
